server:
  port: 8772
#8082
  

spring:  datasource:    url: jdbc:mysql://localhost:3306/VaccinationCenterDB?createDatabaseIfNotExist=true
    password: pass@word1
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
      application:    name: VACCINATION-CENTER-SERVICE