server:
  port: 8771
 #8081

spring:  datasource:    url: jdbc:mysql://localhost:3306/CitizenDB?createDatabaseIfNotExist=true
    password: pass@word1
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver  jpa:    hibernate:      ddl-auto: update    show-sql: true    database-platform: org.hibernate.dialect.MySQL8Dialect

      application:    name: CITIZEN-SERVICE